### PR TITLE
Added footer and footer to landing 

### PR DESCRIPTION
**Pull request by MaicolMicheli12**
i added footer to components and footer to landing

### CODE REVIEW

**Comment by alessandrobelottidev** [comment]
Good afternoon, your pr is fairly good. Please be aware to use Tailwind's proprieties and not custom CSS styles. 

For example change `style="background-color: #32AFEC"` to something like bg-primary.

Same thing for the white background.

**Comment by MaicolMicheli12** [comment]
I think that the footer is now correct, but we need to solve the conflicts

**Comment by alessandrobelottidev** [comment]
Make two separate components for Footer and CtaContainer

**Comment by alessandrobelottidev** [comment]
Great job, I'm going to merge it to the main branch now

**Pull request merged**
